version: '3.8'
name: 'my-mq'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  server:
    build:
      context: ../apps/server
      dockerfile: ../../configs/server.Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
  worker-simple:
    build:
      context: ../apps/worker
      dockerfile: ../../configs/worker.Dockerfile
    restart: always
    environment:
      REDIS_HOST: redis
      QUEUE_NAME: simpleQueue
    depends_on:
      - redis
  worker-repeatable:
    build:
      context: ../apps/worker
      dockerfile: ../../configs/worker.Dockerfile
    restart: always
    environment:
      REDIS_HOST: redis
      QUEUE_NAME: repeatableQueue
    depends_on:
      - redis


